### ISSUE TITLE
Cannot view PDF file?

### ISSUE THREAD

**Issue by lfeng22** [HipSTR-Tool/HipSTR-tutorial#1]
Following the tutorial, I am able to generate the pdf files...however they end up looking like this:
![viz_na12891 copy](https://cloud.githubusercontent.com/assets/28711291/26067537/980cd50a-3968-11e7-86f8-011a9dd7ef1a.jpg)
I don't believe anything went wrong in any of the previous steps and I was able to generate the correct output after using vcftools. However I am getting these errors after creating the pdf files:

/usr/bin/xdg-open: line 402: htmlview: command not found
/usr/bin/xdg-open: line 402: firefox: command not found
/usr/bin/xdg-open: line 402: mozilla: command not found
/usr/bin/xdg-open: line 402: netscape: command not found
/usr/bin/xdg-open: line 402: htmlview: command not found
/usr/bin/xdg-open: line 402: firefox: command not found
/usr/bin/xdg-open: line 402: mozilla: command not found
/usr/bin/xdg-open: line 402: netscape: command not found

Not sure where to go from here. Btw: total newbie to Unix here!

**Comment by tfwillems** [comment]
Looks like it's an issue with the "open" command at the end of the VizAlnPDF scripts. I thought this was pretty standard across must linux/unix distributions, but I may be mistaken. Just to make sure, could you email the generate PDF to hipstrtool@gmail.com. If I can open it on my end, we can confirm this is the issue and go from there?

Thanks!

**Comment by lfeng22** [comment]
I’ve attached the pdf that I generated.

Also, in the HipSTR VizAlnPdf script, it uses the “open” cmd to read the pdf file, but this caused me to get the “could not get a file descriptor referring to the console” error. So, I changed “open” to “xdc-open” in the script to read the pdf file, but the contents are unreadable.

Thanks,

Leila



On May 15, 2017, at 2:58 PM, tfwillems <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like it's an issue with the "open" command at the end of the VizAlnPDF scripts. I thought this was pretty standard across must linux/unix distributions, but I may be mistaken. Just to make sure, could you email the generate PDF to hipstrtool@gmail.com<mailto:hipstrtool@gmail.com>. If I can open it on my end, we can confirm this is the issue and go from there?

Thanks!

**Comment by tfwillems** [comment]
Hi Leila,

I can't seem to reproduce the issue on my end. If you just use the VizAln command instead of VizAlnPdf, does it all still appear all black?

If you comment out line 50 in the VizAlnPdf script (rm $f.svg) and rerun VizAlnPdf, does the viz_NA1289.svg file seem like an ok SVG file (i.e. not all black)?

Best,
Thomas

**Comment by lfeng22** [comment]
Hi Thomas,

When I try to use the VizAln command, I am not able to generate the correct file:

I need to change “HTMLParser” to “html.parser" and "open $f” to “xdg-open $f” to avoid errors in the script, but after I change those, these errors still come up:

/usr/bin/xdg-open: line 402: htmlview: command not found
/usr/bin/xdg-open: line 402: firefox: command not found
/usr/bin/xdg-open: line 402: mozilla: command not found
/usr/bin/xdg-open: line 402: netscape: command not found
/usr/bin/xdg-open: line 402: htmlview: command not found
/usr/bin/xdg-open: line 402: firefox: command not found
/usr/bin/xdg-open: line 402: mozilla: command not found
/usr/bin/xdg-open: line 402: netscape: command not found

When I comment out line 50 in VizAlnPdf script, the svg file is not black. I’m not sure what it is supposed to look like though, I saved a copy as a pdf and attached it in this email.

Thanks,

Leila


On May 15, 2017, at 9:17 PM, tfwillems <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Leila,

I can't seem to reproduce the issue on my end. If you just use the VizAln command instead of VizAlnPdf, does it all still appear all black?

If you comment out line 50 in the VizAlnPdf script (rm $f.svg) and rerun VizAlnPdf, does the viz_NA1289.svg file seem like an ok SVG file (i.e. not all black)?

Best,
Thomas

**Comment by tfwillems** [comment]
@lfeng22 
Hi Leila,

Apologies for not getting back to you sooner regarding this issue. I suspected that there were a number of python3 incompatibilities with the VizAln and VizAlnPdf scripts (they were originally intended for pyhthon2). As a result, I've gone through them and have resolved a number of issues. In my hands, the scripts now work with both python2 and python3 and shouldn't require any modifications.

I haven't incorporated these changes into the **HipSTR-Tool/HipSTR** repository just yet, but they're present in https://github.com/tfwillems/HipSTR. If you could download that repository and see if your visualization issues are now resolved, I'd be very grateful. 

Best,
Thomas

**Comment by lfeng22** [comment]
@tfwillems 
Hi Thomas,

Thanks for resolving the incompatibilities! I am able to generate the PDF files using the resolved scripts now.

Best,
Leila

**Comment by lfeng22** [comment]
@tfwillems<https://github.com/tfwillems>
Hi Thomas,

Thanks for resolving the incompatibilities! I am able to generate the PDF files using the resolved scripts now.

Best,
Leila

On Jul 2, 2017, at 12:20 PM, tfwillems <notifications@github.com<mailto:notifications@github.com>> wrote:


@lfeng22<https://github.com/lfeng22>
Hi Leila,

Apologies for not getting back to you sooner regarding this issue. I suspected that there were a number of python3 incompatibilities with the VizAln and VizAlnPdf scripts (they were originally intended for pyhthon2). As a result, I've gone through them and have resolved a number of issues. In my hands, the scripts now work with both python2 and python3 and shouldn't require any modifications.

I haven't incorporated these changes into the HipSTR-Tool/HipSTR repository just yet, but they're present in https://github.com/tfwillems/HipSTR. If you could download that repository and see if your visualization issues are now resolved, I'd be very grateful.

Best,
Thomas

**Comment by tfwillems** [comment]
@lfeng22 Great, thanks for letting me know!
